### ISSUE TITLE
App stuck on splash screen

### ISSUE THREAD

**Issue by dothedotheg** [biosignalsplux/unity-android-sample#5]
Hello, I was trying to make games in unity for android and I encountered the problem that when exporting a build and test it in android device, it gets stuck on the loading screen.

Do you have any idea why this is happening?

Thank you

**Comment by v-gramos** [comment]
Hello @dothedotheg,

Can you please take a screenshot of the error being printed in the Logcat?
You can follow this [guide](https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html) to access it.

Best regards,
v-gramos

**Comment by GRamosPlux** [comment]
The issue will be closed taking into consideration the important developments achieved and gently shared by @dothedotheg on #4
